### ISSUE TITLE
Is it possible to decrypt aes as used by sops?

### ISSUE THREAD

**Issue by tarasglek** [paulmillr/noble-ciphers#48]
Hi, 
I am trying to use noble to decrypt sops files in deno. I'm not sure if it's a limitation in noble or I'm using it wrong.
Here is the go code that decodes these https://github.com/getsops/sops/blob/73fadcf6b49006b0b77ba811f05eae8d740ed511/aes/cipher.go#L92C2-L92C75

Here is Node.js crypto version that works:
```
import { createDecipheriv } from "crypto";

const uintDecryptionKey = new Uint8Array([
  0x79, 0x82, 0xC4, 0x88, 0xB1, 0x50, 0x9E, 0x98,
  0xD8, 0x92, 0xC5, 0x93, 0x88, 0xAA, 0x70, 0xBF,
  0x6B, 0x0A, 0x87, 0x0F, 0x96, 0x25, 0xBE, 0x45,
  0xA3, 0xF6, 0x98, 0xD9, 0x8A, 0x97, 0xB3, 0x07
]);
const eValue = "ENC[AES256_GCM,data:s0/KBsFec29XLrGbAnLiNA==,iv:k5oP3kb8tTbZaL3PxbFWN8ToOb8vfv2b1EuPz1LbmYU=,tag:n1RlTSRKGgoB909D4I3n+A==,type:str]"
const decryptionKey = Buffer.from(uintDecryptionKey);
const match = eValue.match(
  /^ENC\[AES256_GCM,data:(.+),iv:(.+),tag:(.+),type:(.+)\]/,
);
if (match) {
  const [, encValue, ivBase64, tagBase64, dataType] = match;
  console.log(dataType);
  if (!encValue || !ivBase64 || !tagBase64) {
    throw new Error("Invalid ENC format");
  }

  const iv = Buffer.from(ivBase64, "base64");
  const tag = Buffer.from(tagBase64, "base64");
  console.log(`iv length: ${iv.length}, value: ${iv.toString("base64")}`);
  const decipher = createDecipheriv("aes-256-gcm", decryptionKey, iv);
  decipher.setAuthTag(tag);
  decipher.setAAD(Buffer.from(""));
  const decrypted = decipher.update(encValue, "base64", "utf8");
  console.log(decrypted);
}
```

This outputs 
```
str
iv length: 32, value: k5oP3kb8tTbZaL3PxbFWN8ToOb8vfv2b1EuPz1LbmYU=
this is a secret
```

However I can't decrypt using noble:
```ts
import { gcm } from "@noble/ciphers/aes";
import { base64 } from "@scure/base";

const decryptionKey = new Uint8Array([
  0x79, 0x82, 0xC4, 0x88, 0xB1, 0x50, 0x9E, 0x98,
  0xD8, 0x92, 0xC5, 0x93, 0x88, 0xAA, 0x70, 0xBF,
  0x6B, 0x0A, 0x87, 0x0F, 0x96, 0x25, 0xBE, 0x45,
  0xA3, 0xF6, 0x98, 0xD9, 0x8A, 0x97, 0xB3, 0x07
]);

const eValue = "ENC[AES256_GCM,data:s0/KBsFec29XLrGbAnLiNA==,iv:k5oP3kb8tTbZaL3PxbFWN8ToOb8vfv2b1EuPz1LbmYU=,tag:n1RlTSRKGgoB909D4I3n+A==,type:str]"

const [, encValue, ivBase64, tagBase64, dataType] = eValue.match(
  /^ENC\[AES256_GCM,data:(.+),iv:(.+),tag:(.+),type:(.+)\]/
)!;

console.log('type:', dataType);

const iv = base64.decode(ivBase64);
const tag = base64.decode(tagBase64);
const encrypted = base64.decode(encValue);

console.log(`iv length: ${iv.length}, value: ${ivBase64}`);

const encryptedWithTag = new Uint8Array(encrypted.length + tag.length);
encryptedWithTag.set(encrypted);
encryptedWithTag.set(tag, encrypted.length);

const cipher = gcm(decryptionKey, iv);
const decrypted = await cipher.decrypt(encryptedWithTag);

console.log('decrypted:', new TextDecoder().decode(decrypted));
```

```
type: str
iv length: 32, value: k5oP3kb8tTbZaL3PxbFWN8ToOb8vfv2b1EuPz1LbmYU=
Error: aes/gcm: invalid ghash tag
    at Object.decrypt (file:///Users/taras/Documents/sops-age/node_modules/.pnpm/@noble+ciphers@1.1.3/node_modules/@noble/ciphers/esm/aes.js:574:23)
    at Object.decrypt (file:///Users/taras/Documents/sops-age/node_modules/.pnpm/@noble+ciphers@1.1.3/node_modules/@noble/ciphers/esm/utils.js:219:31)
    at /Users/taras/Documents/sops-age/src/noblest.ts:30:32
```

**Comment by paulmillr** [comment]
Noble ciphers match all necessary specs and vectors, so aes-gcm is compatible with others.

you are doing something wrong somewhere.
